#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-deployment
spec:
  selector:
    matchLabels:
      app: ph-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ph-server
    spec:
      containers:
      - name: ph-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/patidifusa/fastapiph:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ph-service
  name: ph-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ph-server
  type: LoadBalancer